### ISSUE TITLE
Testimonial content not loading into Reviews component

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/inspiredfencing#1]
Hi @jimafisk 
How are you?

I am making good progress on this client site but have run into an issue. 

I am not seeing the content I am trying to load from a component. I am not getting any errors but the ```li``` content I am iterating over is just not visible and not loading in the dom.  

This content in the ```reviews_355.svelte``` file isn't loading;

BTW. The ```{#if}``` statement below was my attempt to conditionally control which quotes I wanted to load based on their id. Though, I don't know if this would work when wanting to load more than 1 quote. Would you append the ```&&``` operator to add more quotes by  their id?
```svelte
      {#each testimonials as testimonial}
      {#if testimonial.fields.quote.id === 1}
        <li class="cs-item">
          <img
            class="cs-quote"
            aria-hidden="true"
            src="https://csimg.nyc3.digitaloceanspaces.com/Reviews/quote-blue.svg"
            decoding="async"
            alt="quote icon"
            width="40"
            height="33"
          />
          <p class="cs-review">
            {@html testimonial.fields.quote.description
              .substring(0, 120)
              .replace(/(<([^>]+)>)/gi, "")}
          </p>
          <span class="cs-name">{testimonial.fields.quote.name}</span>
          <span class="cs-job">{testimonial.fields.quote.location}</span>
        </li>
        {/if}
      {/each}
```
Following are the relevant files:
I am trying to load the ```reviews_355``` [component](https://github.com/jamestagal/inspiredfencing/blob/main/layouts/components/reviews_355.svelte) into the ```_index.json``` which has data from the```testimonials.json```[ file](https://github.com/jamestagal/inspiredfencing/blob/main/content/testimonials.json) content page.

What I want to achieve is to have all the site's testimonials on the ```testimonials``` page and then use that content to dynamically put quotes into other pages based on their id. 

Please have a look if you can. 😺 

Regards,
Ben

**Comment by jamestagal** [comment]
Hi @jimafisk 

Just looking at this one again today and wondered whether I could define the ```quotes``` from the array to display within my content?
So if I could:
1. Set a variable for the content component I wish to display it on:

```svelte
<script>
  let testimonials = allContent.filter(
    (content) => content.type === "testimonials"
  );
</script>
```

2. Loop over the array & use an if statement to only use the ```id```s I wish to display :

Conditional Svelte statement checking for  ```id 1``` and ```id 2```:
Should each id be represented as a string such as  ```"1" && "2"```?

```svelte
{#if testimonial.fields.quote.id === 1 && 2}
```
The whole loop with conditional statement:
```svelte
    <ul class="cs-card-group">
      {#each testimonials as testimonial}
      {#if testimonial.fields.quote.id === 1 && 2}
        <li class="cs-item">
          <img
            class="cs-quote"
            aria-hidden="true"
            src="https://csimg.nyc3.digitaloceanspaces.com/Reviews/quote-blue.svg"
            decoding="async"
            alt="quote icon"
            width="40"
            height="33"
          />
          <p class="cs-review">
            {@html testimonial.fields.quote.description
              .substring(0, 120)
              .replace(/(<([^>]+)>)/gi, "")}
          </p>
          <span class="cs-name">{testimonial.fields.quote.name}</span>
          <span class="cs-job">{testimonial.fields.quote.location}</span>
        </li>
        {/if}
      {/each}
    </ul>
```

**Comment by jamestagal** [comment]
Hi @jimafisk  

I think I know why the content is ```undefined``` and not being displayed....

Maybe because I am trying to bring content from a ```content``` page into a ```component``` but maybe it can only be done the other way round i.e. from a ```component``` into a ```content``` page?  
I'm confused now.... 😀 
Pls help me understand this issue..

Cheers,
Ben

**Comment by jimafisk** [comment]
Hi @jamestagal,

I'm still catching up on some client work, so I'm short on time and only quickly breezed this issue. I'm looking at the "testimonials" section on the homepage (`content/pages/_index.json`), specifically the `layouts/components/reviews_355.svelte` component.

The first thing I'm noticing is there are 2 similar "reviews" components, are these being used for separate things? I think you want these to be the same thing, but the first `reviews_607` is hardcoded for now (probably to review the display) and the second `reviews_355` is one you're trying to convert to a content-driven component.

I see that you're trying to get items from a "single" content type: `content/testimonials.json`. The issue here is that [filter()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/filter) will return an array of items, in this case there will only be one single item. What I think we actually want to loop through is the `testimonials.fields.quote` of the single item that's return - I just updated the code to do that. 

The other problem was subtle, but your condition was checking for an ID that is a number `{#if testimonial.id === 1}` but the ID in your content source is actually a string `{#if testimonial.id === "1"}`. I pushed that change as well.

**Comment by jamestagal** [comment]
Hi @jimafisk 

Thanks for this fix. A follow up question here. 
If I wanted to add more quotes into the component would I add the ```&&```  operator and keep stringing them together? such as ```{#if testimonial.id ==="1" && "2" &&"3"}```  or add commas ```,``` after each quote such as ```{#if testimonial.id ==="1","2","3"}```

**Comment by jimafisk** [comment]
You would have to check each value individually:
```svelte
{#if testimonial.id === "1" && testimonial.id === "2" && testimonial.id === "3"}
```

The problem is this probably wouldn't display anything, since the individual testimonials would have all of these IDs, each would only have one of these IDs (so you probably want "or" `||` instead of "and" `&&`).

Do you need this conditional at all? It would display all the items without it.

**Comment by jamestagal** [comment]
Thanks @jimafisk 

Yes I see. 
So the functionality I am after here is to have the ability to chose a number of testimonials out a the whole list of testimonials that are all displayed on the testimonial page, which come from ```testimonials.json``` but use those chosen ones and display them on various other pages.. I am all about reusing the same quotes not having to duplicate 😀 

So would it look like this?

```svelte
{#if testimonial.id === "1" || testimonial.id === "2" || testimonial.id === "3"}
```

>Do you need this conditional at all? It would display all the items without it.

As for your question, I don't know...but maybe the conditional is good to check that there is the quote of that number and if there isn't it wouldn't be displayed?

**Comment by jamestagal** [comment]
Hi @jimafisk 

I have another question related to these quotes. Its about how to handle adding the periods```...``` to the end of the substring.  I have the following code to reduce the characters to 120 but there is no visual cue to show that the sentence continues..

```svelte
          <p class="cs-review">
            {@html testimonial.description
              ?.substring(0, 120)
              .replace(/(<([^>]+)>)/gi, "")}
          </p>
```

I am thinking that I might have to add a ```<span>``` somehow 

```html
 + '<span > ...</span>';
```
Could you suggest a way to do this?

**Comment by jimafisk** [comment]
What about doing it right in the replace function?

```svelte
<p class="cs-review">
  {@html testimonial.description?.substring(0, 120).replace(/(<([^>]+)>)/gi, "...")}
</p>
```

**Comment by jamestagal** [comment]
Thanks @jimafisk 

I just tried that but doing that didn't work either. 😞

**Comment by jamestagal** [comment]
Hi Jim,

I worked it out. It just needed to be like this: after the bracket. 😄 

```svelte
            {@html testimonial.description
              ?.substring(0, 135)
              .replace(/(<([^>]+)>)/gi, "" ) + ' ...'}
```

**Comment by jamestagal** [comment]
Hi @jimafisk 

Thanks again for looking and this one. 
Now a selected group of testimonial quotes come into other components from the main list of testimonials. 

I only limitation is that once you've chosen which testimonials you what to display it is the same list that is displayed for each because it pulls from the same component. I can only think of two options to make it more flexible in terms of choice of quote.

1. Duplicate the component and re-name it and change the quotes 
2. Set up a randomising function to change the quotes from that main list on a page refresh 

Anyway, I will think about it some more. 😬 

Best regards,
Ben
