### ISSUE TITLE
Help with nav toggle code to close on click - convert Javascript to Svelte

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/inspiredfencing#2]
hi @jimafisk ,

I am trying to add a toggle to the nav to close it when you click on any nav item when on mobile.
But when I add the class to the ```li``` it doesn't work:
Pls help if you can.

Here is the Javascript code I want to convert from.
```Javascript
// mobile nav toggle code
const dropDowns = Array.from(document.querySelectorAll('#cs-navigation .cs-dropdown'));
    for (const item of dropDowns) {
        const onClick = () => {
        item.classList.toggle('cs-active')
    }
    item.addEventListener('click', onClick)
    }

```

Below is the line I have added to try to make this work:  I think I need to add the class ```cs-active``` to the ```li```. see below.

```svelte

class:cs-active={activeItem === 'home'}

```
Here is a code snippet with that line included: which sits in the ```header_2.svelte``` [file](https://github.com/jamestagal/inspiredfencing/blob/main/layouts/global/header_2.svelte).

```svelte
      <ul id="cs-expanded" class="cs-ul" aria-expanded="false">
          <li on:click={() => setActive("home")} class:cs-active={activeItem === 'home'} class="cs-li">
            <a
              href="."
              class="cs-li-link {activeItem.id === 'home' ? 'cs-active' : ''}"
            >
              Home
            </a>
          </li>
        <!-- Rest of  list items -->
     </ul>

``` 
BTW. I am testing locally and haven't push any changes yet!

Cheers,
Ben

**Comment by jimafisk** [comment]
@jamestagal - I haven't taken a look at this yet, but can you please push all code you want me to look at to the repo first? The easiest way for me to debug things is just to run it locally. Thanks!

**Comment by jamestagal** [comment]
Thanks Jim,

Actually I had pushed that change a while ago but didn't update my message here. Sorry. 
It's on the following line of code.
https://github.com/jamestagal/inspiredfencing/blob/056c4f6da597012e76c22911edf5831e79a1e0f5/layouts/global/header_2.svelte#L112

**Comment by jamestagal** [comment]
Hi @jimafisk 

At present, I have pushed the code I have been trying out to get this ```close``` functionality to work. I am still struggling to get the nav menu to close when any one of the nav items is clicked.  

I have been trying to tap into the function that already sets the active state of the ```li```s in the nav menu to close the menu but I am not getting anywhere. 

Please have a look when you get a chance. I would appreciate it.

Best regards,
Ben

**Comment by jimafisk** [comment]
@jamestagal it looks like you were missing some necessary class changes, I just pushed a fix for this. It also looked like the logic in `setActiveAndToggle()` was overwriting itself and probably not doing exactly what you wanted it to do, so I simplified `activeItem` from an object into a string to make this easier to follow.

**Comment by jamestagal** [comment]
Thanks Jim,

Actually I guess the goal would be to not use the ```nav.js``` file and convert any other functions over into Svelte style code. 
I will slowly get there 😄 

Thanks again.
